// 三年级下册（外研版2024）单词表
const BOOK_TITLE = "📚 三年级下册（外研版）";
const STORAGE_KEY = "vocabApp_grade3b";
const BOOK_WORDS = [
  // Unit 1 Animal friends
  {word:"animal",phonetic:"/ˈænɪml/",meaning:"动物",example:"I like this animal.",exampleCn:"我喜欢这个动物。",category:"Unit 1"},
  {word:"panda",phonetic:"/ˈpændə/",meaning:"大熊猫",example:"The panda is cute.",exampleCn:"大熊猫很可爱。",category:"Unit 1"},
  {word:"elephant",phonetic:"/ˈelɪfənt/",meaning:"象",example:"The elephant is big.",exampleCn:"大象很大。",category:"Unit 1"},
  {word:"bear",phonetic:"/beər/",meaning:"熊",example:"Look at the bear.",exampleCn:"看那只熊。",category:"Unit 1"},
  {word:"giraffe",phonetic:"/dʒɪˈrɑːf/",meaning:"长颈鹿",example:"The giraffe is tall.",exampleCn:"长颈鹿很高。",category:"Unit 1"},
  {word:"monkey",phonetic:"/ˈmʌŋki/",meaning:"猴",example:"The monkey is funny.",exampleCn:"猴子很有趣。",category:"Unit 1"},
  {word:"them",phonetic:"/ðem/",meaning:"他们；她们；它们",example:"I like them.",exampleCn:"我喜欢它们。",category:"Unit 1"},
  {word:"draw",phonetic:"/drɔː/",meaning:"画，绘画",example:"I can draw a panda.",exampleCn:"我能画一只熊猫。",category:"Unit 1"},
  {word:"tiger",phonetic:"/ˈtaɪɡər/",meaning:"老虎，虎",example:"The tiger is strong.",exampleCn:"老虎很强壮。",category:"Unit 1"},
  {word:"strong",phonetic:"/strɒŋ/",meaning:"强壮的，力气大的",example:"The bear is strong.",exampleCn:"熊很强壮。",category:"Unit 1"},
  {word:"short",phonetic:"/ʃɔːrt/",meaning:"个子矮的",example:"The monkey is short.",exampleCn:"猴子个子矮。",category:"Unit 1"},
  {word:"white",phonetic:"/waɪt/",meaning:"白的，白色的",example:"The bear is white.",exampleCn:"熊是白色的。",category:"Unit 1"},
  {word:"brown",phonetic:"/braʊn/",meaning:"棕色的；褐色的",example:"The monkey is brown.",exampleCn:"猴子是棕色的。",category:"Unit 1"},
  {word:"tall",phonetic:"/tɔːl/",meaning:"高的，高大的",example:"The giraffe is tall.",exampleCn:"长颈鹿很高。",category:"Unit 1"},
  {word:"him",phonetic:"/hɪm/",meaning:"他；它（指雄性动物）",example:"Look at him.",exampleCn:"看他。",category:"Unit 1"},
  {word:"ostrich",phonetic:"/ˈɒstrɪtʃ/",meaning:"鸵鸟",example:"The ostrich is fast.",exampleCn:"鸵鸟跑得快。",category:"Unit 1"},
  {word:"fast",phonetic:"/fɑːst/",meaning:"快的，快速的",example:"The tiger is fast.",exampleCn:"老虎跑得快。",category:"Unit 1"},
  {word:"chameleon",phonetic:"/kəˈmiːliən/",meaning:"变色龙",example:"Look at the chameleon.",exampleCn:"看那只变色龙。",category:"Unit 1"},
  {word:"small",phonetic:"/smɔːl/",meaning:"小的",example:"The monkey is small.",exampleCn:"猴子很小。",category:"Unit 1"},
  {word:"lion",phonetic:"/ˈlaɪən/",meaning:"狮子",example:"The lion is strong.",exampleCn:"狮子很强壮。",category:"Unit 1"},
  {word:"cute",phonetic:"/kjuːt/",meaning:"可爱的，漂亮的，逗人喜爱的",example:"The panda is cute.",exampleCn:"熊猫很可爱。",category:"Unit 1"},
  {word:"out",phonetic:"/aʊt/",meaning:"往外，向外，出来",example:"Let's go out.",exampleCn:"我们出去吧。",category:"Unit 1"},
  {word:"zoo",phonetic:"/zuː/",meaning:"动物园",example:"Let's go to the zoo.",exampleCn:"我们去动物园吧。",category:"Unit 1"},
  {word:"go",phonetic:"/ɡoʊ/",meaning:"走，去",example:"Let's go.",exampleCn:"我们走吧。",category:"Unit 1"},
  {word:"zebra",phonetic:"/ˈziːbrə/",meaning:"斑马",example:"The zebra is white and black.",exampleCn:"斑马是黑白色的。",category:"Unit 1"},
  {word:"move",phonetic:"/muːv/",meaning:"移动",example:"Don't move.",exampleCn:"别动。",category:"Unit 1"},
  {word:"road",phonetic:"/roʊd/",meaning:"路，道路",example:"Cross the road.",exampleCn:"过马路。",category:"Unit 1"},
  {word:"dance",phonetic:"/dɑːns/",meaning:"跳舞",example:"I can dance.",exampleCn:"我会跳舞。",category:"Unit 1"},
  {word:"along",phonetic:"/əˈlɒŋ/",meaning:"向前",example:"Walk along the road.",exampleCn:"沿着路走。",category:"Unit 1"},
  {word:"which",phonetic:"/wɪtʃ/",meaning:"哪一个；哪些",example:"Which animal do you like?",exampleCn:"你喜欢哪个动物？",category:"Unit 1"},
  {word:"word",phonetic:"/wɜːrd/",meaning:"字，词，单词",example:"Read the word.",exampleCn:"读这个单词。",category:"Unit 1"},
  {word:"stone",phonetic:"/stoʊn/",meaning:"石头",example:"It's a stone.",exampleCn:"这是一块石头。",category:"Unit 1"},
  {word:"hat",phonetic:"/hæt/",meaning:"帽子",example:"I have a hat.",exampleCn:"我有一顶帽子。",category:"Unit 1"},
  {word:"shoe",phonetic:"/ʃuː/",meaning:"鞋",example:"I like my shoes.",exampleCn:"我喜欢我的鞋。",category:"Unit 1"},

  // Unit 2 Know your body
  {word:"body",phonetic:"/ˈbɒdi/",meaning:"身体",example:"This is my body.",exampleCn:"这是我的身体。",category:"Unit 2"},
  {word:"head",phonetic:"/hed/",meaning:"头，头部",example:"Touch your head.",exampleCn:"摸摸你的头。",category:"Unit 2"},
  {word:"eye",phonetic:"/aɪ/",meaning:"眼睛",example:"I have two eyes.",exampleCn:"我有两只眼睛。",category:"Unit 2"},
  {word:"ear",phonetic:"/ɪər/",meaning:"耳朵",example:"I have two ears.",exampleCn:"我有两只耳朵。",category:"Unit 2"},
  {word:"mouth",phonetic:"/maʊθ/",meaning:"嘴，口",example:"Open your mouth.",exampleCn:"张开你的嘴。",category:"Unit 2"},
  {word:"nose",phonetic:"/noʊz/",meaning:"鼻子",example:"Touch your nose.",exampleCn:"摸摸你的鼻子。",category:"Unit 2"},
  {word:"touch",phonetic:"/tʌtʃ/",meaning:"触摸，碰",example:"Touch your head.",exampleCn:"摸摸你的头。",category:"Unit 2"},
  {word:"hand",phonetic:"/hænd/",meaning:"手",example:"Wash your hands.",exampleCn:"洗洗你的手。",category:"Unit 2"},
  {word:"arm",phonetic:"/ɑːrm/",meaning:"手臂，上肢",example:"Move your arms.",exampleCn:"动动你的手臂。",category:"Unit 2"},
  {word:"leg",phonetic:"/leɡ/",meaning:"腿",example:"Move your legs.",exampleCn:"动动你的腿。",category:"Unit 2"},
  {word:"foot",phonetic:"/fʊt/",meaning:"（复数feet）脚",example:"Stamp your feet.",exampleCn:"跺跺你的脚。",category:"Unit 2"},
  {word:"toe",phonetic:"/toʊ/",meaning:"脚趾",example:"Touch your toes.",exampleCn:"摸摸你的脚趾。",category:"Unit 2"},
  {word:"get",phonetic:"/ɡet/",meaning:"获得，得到",example:"Get the ball.",exampleCn:"拿到球。",category:"Unit 2"},
  {word:"snowy",phonetic:"/ˈsnoʊi/",meaning:"多雪的，积雪的",example:"It's snowy today.",exampleCn:"今天下雪了。",category:"Unit 2"},
  {word:"child",phonetic:"/tʃaɪld/",meaning:"（复数children）儿童，小孩",example:"The child is happy.",exampleCn:"这个小孩很开心。",category:"Unit 2"},
  {word:"work",phonetic:"/wɜːrk/",meaning:"事情，工作",example:"Good work!",exampleCn:"干得好！",category:"Unit 2"},
  {word:"snowman",phonetic:"/ˈsnoʊmæn/",meaning:"雪人",example:"Let's make a snowman.",exampleCn:"我们来堆雪人吧。",category:"Unit 2"},
  {word:"long",phonetic:"/lɒŋ/",meaning:"长的",example:"It has long arms.",exampleCn:"它有长长的手臂。",category:"Unit 2"},
  {word:"rock",phonetic:"/rɒk/",meaning:"石头，石子",example:"It's a big rock.",exampleCn:"这是一块大石头。",category:"Unit 2"},
  {word:"cool",phonetic:"/kuːl/",meaning:"时髦的，酷的",example:"That's cool!",exampleCn:"太酷了！",category:"Unit 2"},
  {word:"best",phonetic:"/best/",meaning:"最好的",example:"You're the best.",exampleCn:"你是最棒的。",category:"Unit 2"},
  {word:"part",phonetic:"/pɑːrt/",meaning:"部分",example:"This is a part of the body.",exampleCn:"这是身体的一部分。",category:"Unit 2"},
  {word:"well",phonetic:"/wel/",meaning:"嗯，这个；健康的",example:"Well, let me see.",exampleCn:"嗯，让我看看。",category:"Unit 2"},
  {word:"hear",phonetic:"/hɪər/",meaning:"听见",example:"I can hear you.",exampleCn:"我能听见你。",category:"Unit 2"},
  {word:"smell",phonetic:"/smel/",meaning:"闻到，嗅到",example:"I can smell flowers.",exampleCn:"我能闻到花香。",category:"Unit 2"},
  {word:"talk",phonetic:"/tɔːk/",meaning:"讨论，商谈",example:"Let's talk.",exampleCn:"我们来谈谈。",category:"Unit 2"},
  {word:"eat",phonetic:"/iːt/",meaning:"吃",example:"I eat an apple.",exampleCn:"我吃一个苹果。",category:"Unit 2"},
  {word:"hey",phonetic:"/heɪ/",meaning:"嘿，喂",example:"Hey, come here!",exampleCn:"嘿，过来！",category:"Unit 2"},
  {word:"stop",phonetic:"/stɒp/",meaning:"停止，终止",example:"Stop talking.",exampleCn:"别说了。",category:"Unit 2"},
  {word:"important",phonetic:"/ɪmˈpɔːrtənt/",meaning:"重要的，重大的",example:"It's important.",exampleCn:"这很重要。",category:"Unit 2"},
  {word:"team",phonetic:"/tiːm/",meaning:"队",example:"We are a team.",exampleCn:"我们是一个团队。",category:"Unit 2"},
  {word:"dream",phonetic:"/driːm/",meaning:"梦",example:"I have a dream.",exampleCn:"我有一个梦想。",category:"Unit 2"},
  {word:"ask",phonetic:"/ɑːsk/",meaning:"问，提问",example:"Ask me a question.",exampleCn:"问我一个问题。",category:"Unit 2"},
  {word:"answer",phonetic:"/ˈɑːnsər/",meaning:"回答，答复",example:"Answer the question.",exampleCn:"回答这个问题。",category:"Unit 2"},
  {word:"hair",phonetic:"/heər/",meaning:"头发",example:"She has long hair.",exampleCn:"她有长头发。",category:"Unit 2"},
  {word:"different",phonetic:"/ˈdɪfrənt/",meaning:"不同的，不一样的，有差异的",example:"They are different.",exampleCn:"它们是不同的。",category:"Unit 2"},
  {word:"face",phonetic:"/feɪs/",meaning:"脸",example:"Wash your face.",exampleCn:"洗洗你的脸。",category:"Unit 2"},

  // Unit 3 Yummy food
  {word:"yummy",phonetic:"/ˈjʌmi/",meaning:"美味的，很好吃的",example:"It's yummy!",exampleCn:"真好吃！",category:"Unit 3"},
  {word:"food",phonetic:"/fuːd/",meaning:"食物",example:"I like food.",exampleCn:"我喜欢食物。",category:"Unit 3"},
  {word:"strawberry",phonetic:"/ˈstrɔːbəri/",meaning:"草莓",example:"I like strawberries.",exampleCn:"我喜欢草莓。",category:"Unit 3"},
  {word:"tomato",phonetic:"/təˈmeɪtoʊ/",meaning:"番茄，西红柿",example:"I like tomatoes.",exampleCn:"我喜欢西红柿。",category:"Unit 3"},
  {word:"noodle",phonetic:"/ˈnuːdl/",meaning:"面条",example:"I like noodles.",exampleCn:"我喜欢面条。",category:"Unit 3"},
  {word:"carrot",phonetic:"/ˈkærət/",meaning:"胡萝卜",example:"Eat your carrots.",exampleCn:"吃你的胡萝卜。",category:"Unit 3"},
  {word:"chicken",phonetic:"/ˈtʃɪkɪn/",meaning:"鸡肉；鸡",example:"I like chicken.",exampleCn:"我喜欢鸡肉。",category:"Unit 3"},
  {word:"fish",phonetic:"/fɪʃ/",meaning:"鱼肉；鱼",example:"I like fish.",exampleCn:"我喜欢鱼。",category:"Unit 3"},
  {word:"rice",phonetic:"/raɪs/",meaning:"米；米饭",example:"I eat rice every day.",exampleCn:"我每天吃米饭。",category:"Unit 3"},
  {word:"meat",phonetic:"/miːt/",meaning:"肉",example:"Do you like meat?",exampleCn:"你喜欢肉吗？",category:"Unit 3"},
  {word:"fruit",phonetic:"/fruːt/",meaning:"水果",example:"Eat more fruit.",exampleCn:"多吃水果。",category:"Unit 3"},
  {word:"vegetable",phonetic:"/ˈvedʒtəbl/",meaning:"蔬菜",example:"Eat your vegetables.",exampleCn:"吃你的蔬菜。",category:"Unit 3"},
  {word:"salad",phonetic:"/ˈsæləd/",meaning:"沙拉",example:"I like salad.",exampleCn:"我喜欢沙拉。",category:"Unit 3"},
  {word:"banana",phonetic:"/bəˈnɑːnə/",meaning:"香蕉",example:"I like bananas.",exampleCn:"我喜欢香蕉。",category:"Unit 3"},
  {word:"bean",phonetic:"/biːn/",meaning:"豆子",example:"I like beans.",exampleCn:"我喜欢豆子。",category:"Unit 3"},
  {word:"cucumber",phonetic:"/ˈkjuːkʌmbər/",meaning:"黄瓜",example:"I like cucumbers.",exampleCn:"我喜欢黄瓜。",category:"Unit 3"},
  {word:"then",phonetic:"/ðen/",meaning:"那么；然后，接下来",example:"Then let's eat.",exampleCn:"那我们吃吧。",category:"Unit 3"},
  {word:"about",phonetic:"/əˈbaʊt/",meaning:"关于",example:"What about you?",exampleCn:"你呢？",category:"Unit 3"},
  {word:"what about...",phonetic:"/wɒt əˈbaʊt/",meaning:"……怎么样",example:"What about some rice?",exampleCn:"来点米饭怎么样？",category:"Unit 3"},
  {word:"grape",phonetic:"/ɡreɪp/",meaning:"葡萄",example:"I like grapes.",exampleCn:"我喜欢葡萄。",category:"Unit 3"},
  {word:"juice",phonetic:"/dʒuːs/",meaning:"汁",example:"I like orange juice.",exampleCn:"我喜欢橙汁。",category:"Unit 3"},
  {word:"why",phonetic:"/waɪ/",meaning:"为什么",example:"Why do you like it?",exampleCn:"你为什么喜欢它？",category:"Unit 3"},
  {word:"early",phonetic:"/ˈɜːrli/",meaning:"早的；提早，提前",example:"Get up early.",exampleCn:"早点起床。",category:"Unit 3"},
  {word:"breakfast",phonetic:"/ˈbrekfəst/",meaning:"早餐，早饭",example:"Have breakfast.",exampleCn:"吃早餐。",category:"Unit 3"},
  {word:"time",phonetic:"/taɪm/",meaning:"时间",example:"It's time for lunch.",exampleCn:"该吃午饭了。",category:"Unit 3"},
  {word:"still",phonetic:"/stɪl/",meaning:"还，仍然",example:"I'm still hungry.",exampleCn:"我还饿。",category:"Unit 3"},
  {word:"ready",phonetic:"/ˈredi/",meaning:"准备好的",example:"Are you ready?",exampleCn:"你准备好了吗？",category:"Unit 3"},
  {word:"corn",phonetic:"/kɔːrn/",meaning:"玉米",example:"I like corn.",exampleCn:"我喜欢玉米。",category:"Unit 3"},
  {word:"lunch",phonetic:"/lʌntʃ/",meaning:"午餐",example:"It's time for lunch.",exampleCn:"该吃午餐了。",category:"Unit 3"},
  {word:"very",phonetic:"/ˈveri/",meaning:"很，非常",example:"It's very yummy.",exampleCn:"非常好吃。",category:"Unit 3"},
  {word:"much",phonetic:"/mʌtʃ/",meaning:"大量",example:"Thank you very much.",exampleCn:"非常感谢你。",category:"Unit 3"},

  // Unit 4 What's your hobby?
  {word:"hobby",phonetic:"/ˈhɒbi/",meaning:"业余爱好，嗜好",example:"What's your hobby?",exampleCn:"你的爱好是什么？",category:"Unit 4"},
  {word:"his",phonetic:"/hɪz/",meaning:"他的",example:"His hobby is reading.",exampleCn:"他的爱好是阅读。",category:"Unit 4"},
  {word:"grow",phonetic:"/ɡroʊ/",meaning:"成长，长大",example:"I want to grow up.",exampleCn:"我想长大。",category:"Unit 4"},
  {word:"grow up",phonetic:"/ɡroʊ ʌp/",meaning:"长大",example:"What do you want to be when you grow up?",exampleCn:"你长大想做什么？",category:"Unit 4"},
  {word:"garden",phonetic:"/ˈɡɑːrdn/",meaning:"做园艺工作；花园",example:"I like to garden.",exampleCn:"我喜欢做园艺。",category:"Unit 4"},
  {word:"insect",phonetic:"/ˈɪnsekt/",meaning:"昆虫",example:"I like insects.",exampleCn:"我喜欢昆虫。",category:"Unit 4"},
  {word:"interesting",phonetic:"/ˈɪntrəstɪŋ/",meaning:"有趣的，吸引人的",example:"It's interesting.",exampleCn:"这很有趣。",category:"Unit 4"},
  {word:"kite",phonetic:"/kaɪt/",meaning:"风筝",example:"I like flying kites.",exampleCn:"我喜欢放风筝。",category:"Unit 4"},
  {word:"learn",phonetic:"/lɜːrn/",meaning:"学习",example:"I learn English.",exampleCn:"我学英语。",category:"Unit 4"},
  {word:"man",phonetic:"/mæn/",meaning:"成年男子，男人",example:"The man is tall.",exampleCn:"这个男人很高。",category:"Unit 4"},
  {word:"mantis",phonetic:"/ˈmæntɪs/",meaning:"螳螂",example:"Look at the mantis.",exampleCn:"看那只螳螂。",category:"Unit 4"},
  {word:"milk",phonetic:"/mɪlk/",meaning:"奶，牛奶",example:"I drink milk.",exampleCn:"我喝牛奶。",category:"Unit 4"},
  {word:"plant",phonetic:"/plɑːnt/",meaning:"植物",example:"I like plants.",exampleCn:"我喜欢植物。",category:"Unit 4"},
  {word:"question",phonetic:"/ˈkwestʃən/",meaning:"问题，疑问",example:"I have a question.",exampleCn:"我有一个问题。",category:"Unit 4"},
  {word:"robot",phonetic:"/ˈroʊbɒt/",meaning:"机器人",example:"I like robots.",exampleCn:"我喜欢机器人。",category:"Unit 4"},
  {word:"country",phonetic:"/ˈkʌntri/",meaning:"国家",example:"China is a big country.",exampleCn:"中国是一个大国。",category:"Unit 4"},
  {word:"cupcake",phonetic:"/ˈkʌpkeɪk/",meaning:"杯形蛋糕",example:"I like cupcakes.",exampleCn:"我喜欢杯形蛋糕。",category:"Unit 4"},
  {word:"dumpling",phonetic:"/ˈdʌmplɪŋ/",meaning:"水饺",example:"I like dumplings.",exampleCn:"我喜欢水饺。",category:"Unit 4"},
  {word:"every",phonetic:"/ˈevri/",meaning:"每，每逢，每隔",example:"I read every day.",exampleCn:"我每天读书。",category:"Unit 4"},
  {word:"free",phonetic:"/friː/",meaning:"空闲的，有空的",example:"Are you free today?",exampleCn:"你今天有空吗？",category:"Unit 4"},
  {word:"hot",phonetic:"/hɒt/",meaning:"热的",example:"It's hot today.",exampleCn:"今天很热。",category:"Unit 4"},
  {word:"hot dog",phonetic:"/hɒt dɒɡ/",meaning:"热狗",example:"I like hot dogs.",exampleCn:"我喜欢热狗。",category:"Unit 4"},
  {word:"ice",phonetic:"/aɪs/",meaning:"冰",example:"I like ice cream.",exampleCn:"我喜欢冰淇淋。",category:"Unit 4"},

  // Unit 5 What time is it?
  {word:"o'clock",phonetic:"/əˈklɒk/",meaning:"点钟",example:"It's three o'clock.",exampleCn:"三点钟了。",category:"Unit 5"},
  {word:"clock",phonetic:"/klɒk/",meaning:"时钟",example:"Look at the clock.",exampleCn:"看看时钟。",category:"Unit 5"},
  {word:"half",phonetic:"/hɑːf/",meaning:"一半，半",example:"It's half past one.",exampleCn:"一点半了。",category:"Unit 5"},
  {word:"half past one/two...",phonetic:"/hɑːf pɑːst/",meaning:"1点半/2点半等",example:"It's half past two.",exampleCn:"两点半了。",category:"Unit 5"},
  {word:"fifteen",phonetic:"/ˌfɪfˈtiːn/",meaning:"十五",example:"It's fifteen past three.",exampleCn:"三点十五了。",category:"Unit 5"},
  {word:"forty-five",phonetic:"/ˌfɔːrtiˈfaɪv/",meaning:"四十五",example:"It's forty-five past two.",exampleCn:"两点四十五了。",category:"Unit 5"},
  {word:"after",phonetic:"/ˈɑːftər/",meaning:"在……后",example:"After school.",exampleCn:"放学后。",category:"Unit 5"},
  {word:"afternoon",phonetic:"/ˌɑːftərˈnuːn/",meaning:"下午，午后",example:"Good afternoon.",exampleCn:"下午好。",category:"Unit 5"},
  {word:"afternoon tea",phonetic:"/ˌɑːftərˈnuːn tiː/",meaning:"下午茶",example:"Let's have afternoon tea.",exampleCn:"我们喝下午茶吧。",category:"Unit 5"},
  {word:"dinner",phonetic:"/ˈdɪnər/",meaning:"正餐，主餐",example:"It's time for dinner.",exampleCn:"该吃晚餐了。",category:"Unit 5"},
  {word:"cake",phonetic:"/keɪk/",meaning:"蛋糕",example:"I like cake.",exampleCn:"我喜欢蛋糕。",category:"Unit 5"},
  {word:"beef",phonetic:"/biːf/",meaning:"牛肉",example:"I like beef.",exampleCn:"我喜欢牛肉。",category:"Unit 5"},
  {word:"soup",phonetic:"/suːp/",meaning:"汤",example:"I like soup.",exampleCn:"我喜欢汤。",category:"Unit 5"},
  {word:"a lot",phonetic:"/ə lɒt/",meaning:"大量，许多",example:"I eat a lot.",exampleCn:"我吃了很多。",category:"Unit 5"},
  {word:"past",phonetic:"/pɑːst/",meaning:"晚于；在……之后",example:"It's half past one.",exampleCn:"一点半了。",category:"Unit 5"},
  {word:"urgh",phonetic:"/ɜːɡ/",meaning:"呃，呸",example:"Urgh! I don't like it.",exampleCn:"呸！我不喜欢。",category:"Unit 5"},
  {word:"homework",phonetic:"/ˈhoʊmwɜːrk/",meaning:"家庭作业，功课",example:"Do your homework.",exampleCn:"做你的作业。",category:"Unit 5"},
  {word:"need",phonetic:"/niːd/",meaning:"需要",example:"I need help.",exampleCn:"我需要帮助。",category:"Unit 5"},
  {word:"activity",phonetic:"/ækˈtɪvəti/",meaning:"活动",example:"It's a fun activity.",exampleCn:"这是一个有趣的活动。",category:"Unit 5"},
  {word:"her",phonetic:"/hɜːr/",meaning:"她的",example:"This is her book.",exampleCn:"这是她的书。",category:"Unit 5"},
  {word:"class",phonetic:"/klɑːs/",meaning:"课；班级",example:"I like this class.",exampleCn:"我喜欢这节课。",category:"Unit 5"},
  {word:"evening",phonetic:"/ˈiːvnɪŋ/",meaning:"傍晚；晚上",example:"Good evening.",exampleCn:"晚上好。",category:"Unit 5"},
  {word:"call",phonetic:"/kɔːl/",meaning:"（给……）打电话",example:"Call me later.",exampleCn:"晚点给我打电话。",category:"Unit 5"},

  // Unit 6 A great week
  {word:"Monday",phonetic:"/ˈmʌndeɪ/",meaning:"星期一",example:"I have English on Monday.",exampleCn:"我星期一有英语课。",category:"Unit 6"},
  {word:"Tuesday",phonetic:"/ˈtjuːzdeɪ/",meaning:"星期二",example:"It's Tuesday today.",exampleCn:"今天是星期二。",category:"Unit 6"},
  {word:"Wednesday",phonetic:"/ˈwenzdeɪ/",meaning:"星期三",example:"I play football on Wednesday.",exampleCn:"我星期三踢足球。",category:"Unit 6"},
  {word:"Thursday",phonetic:"/ˈθɜːrzdeɪ/",meaning:"星期四",example:"Thursday is my favourite day.",exampleCn:"星期四是我最喜欢的一天。",category:"Unit 6"},
  {word:"Friday",phonetic:"/ˈfraɪdeɪ/",meaning:"星期五",example:"It's Friday!",exampleCn:"星期五了！",category:"Unit 6"},
  {word:"Saturday",phonetic:"/ˈsætərdeɪ/",meaning:"星期六",example:"I go to the park on Saturday.",exampleCn:"我星期六去公园。",category:"Unit 6"},
  {word:"Sunday",phonetic:"/ˈsʌndeɪ/",meaning:"星期日",example:"Sunday is fun.",exampleCn:"星期天很有趣。",category:"Unit 6"},
  {word:"park",phonetic:"/pɑːrk/",meaning:"公园",example:"Let's go to the park.",exampleCn:"我们去公园吧。",category:"Unit 6"},
  {word:"visit",phonetic:"/ˈvɪzɪt/",meaning:"看望，拜访",example:"I visit my grandma.",exampleCn:"我去看望奶奶。",category:"Unit 6"},
  {word:"lesson",phonetic:"/ˈlesn/",meaning:"课，课程",example:"I have a piano lesson.",exampleCn:"我有一节钢琴课。",category:"Unit 6"},
  {word:"football",phonetic:"/ˈfʊtbɔːl/",meaning:"足球",example:"I play football.",exampleCn:"我踢足球。",category:"Unit 6"},
  {word:"art",phonetic:"/ɑːrt/",meaning:"美术，艺术",example:"I like art.",exampleCn:"我喜欢美术。",category:"Unit 6"},
  {word:"subject",phonetic:"/ˈsʌbdʒekt/",meaning:"学科",example:"What's your favourite subject?",exampleCn:"你最喜欢的学科是什么？",category:"Unit 6"},
  {word:"something",phonetic:"/ˈsʌmθɪŋ/",meaning:"某物；某事",example:"I want something to eat.",exampleCn:"我想吃点东西。",category:"Unit 6"},
  {word:"idea",phonetic:"/aɪˈdɪə/",meaning:"想法，主意",example:"Good idea!",exampleCn:"好主意！",category:"Unit 6"},
  {word:"soon",phonetic:"/suːn/",meaning:"不久，即刻，很快",example:"See you soon.",exampleCn:"很快见。",category:"Unit 6"},
  {word:"teach",phonetic:"/tiːtʃ/",meaning:"教，教授",example:"She can teach English.",exampleCn:"她能教英语。",category:"Unit 6"},
  {word:"English",phonetic:"/ˈɪŋɡlɪʃ/",meaning:"英语",example:"I like English.",exampleCn:"我喜欢英语。",category:"Unit 6"},
  {word:"card",phonetic:"/kɑːrd/",meaning:"卡片",example:"Make a card.",exampleCn:"做一张卡片。",category:"Unit 6"},
  {word:"busy",phonetic:"/ˈbɪzi/",meaning:"忙的，忙碌的",example:"I'm busy today.",exampleCn:"我今天很忙。",category:"Unit 6"},
  {word:"old",phonetic:"/oʊld/",meaning:"年老的；相识很久的",example:"He is old.",exampleCn:"他年纪大了。",category:"Unit 6"},
  {word:"some",phonetic:"/sʌm/",meaning:"一些，若干",example:"I have some books.",exampleCn:"我有一些书。",category:"Unit 6"},
  {word:"bookmark",phonetic:"/ˈbʊkmɑːrk/",meaning:"书签",example:"I make a bookmark.",exampleCn:"我做了一个书签。",category:"Unit 6"},
  {word:"stick",phonetic:"/stɪk/",meaning:"木棍，拐杖",example:"He has a stick.",exampleCn:"他有一根拐杖。",category:"Unit 6"},
  {word:"sure",phonetic:"/ʃʊr/",meaning:"当然，好的",example:"Sure, no problem.",exampleCn:"当然，没问题。",category:"Unit 6"},
  {word:"flower",phonetic:"/ˈflaʊər/",meaning:"花，花朵",example:"I like flowers.",exampleCn:"我喜欢花。",category:"Unit 6"},
  {word:"afterschool",phonetic:"/ˈɑːftərskuːl/",meaning:"课外的",example:"I have afterschool activities.",exampleCn:"我有课外活动。",category:"Unit 6"},
  {word:"club",phonetic:"/klʌb/",meaning:"俱乐部",example:"I'm in the art club.",exampleCn:"我在美术俱乐部。",category:"Unit 6"},
  {word:"piano",phonetic:"/piˈænoʊ/",meaning:"钢琴",example:"I play the piano.",exampleCn:"我弹钢琴。",category:"Unit 6"},
  {word:"basketball",phonetic:"/ˈbɑːskɪtbɔːl/",meaning:"篮球",example:"I play basketball.",exampleCn:"我打篮球。",category:"Unit 6"},
  {word:"computer",phonetic:"/kəmˈpjuːtər/",meaning:"计算机；电脑",example:"I use a computer.",exampleCn:"我用电脑。",category:"Unit 6"},
  {word:"music",phonetic:"/ˈmjuːzɪk/",meaning:"音乐",example:"I like music.",exampleCn:"我喜欢音乐。",category:"Unit 6"},
  {word:"science",phonetic:"/ˈsaɪəns/",meaning:"科学",example:"I like science.",exampleCn:"我喜欢科学。",category:"Unit 6"},
  {word:"week",phonetic:"/wiːk/",meaning:"星期，周",example:"I have a great week.",exampleCn:"我度过了很棒的一周。",category:"Unit 6"},
  {word:"watch",phonetic:"/wɒtʃ/",meaning:"观察",example:"Watch me.",exampleCn:"看我。",category:"Unit 6"},
  {word:"when",phonetic:"/wen/",meaning:"什么时候",example:"When is the class?",exampleCn:"什么时候上课？",category:"Unit 6"},

  // Plays 课本剧词汇
  {word:"fox",phonetic:"/fɒks/",meaning:"狐狸",example:"The fox is clever.",exampleCn:"狐狸很聪明。",category:"Plays"},
  {word:"jump",phonetic:"/dʒʌmp/",meaning:"跳",example:"Jump high!",exampleCn:"跳高！",category:"Plays"},
  {word:"yum",phonetic:"/jʌm/",meaning:"嗯（表示味道非常好）",example:"Yum! It's delicious.",exampleCn:"嗯！真好吃。",category:"Plays"},
  {word:"king",phonetic:"/kɪŋ/",meaning:"国王",example:"He is the king.",exampleCn:"他是国王。",category:"Plays"},
  {word:"forest",phonetic:"/ˈfɒrɪst/",meaning:"森林",example:"The fox lives in the forest.",exampleCn:"狐狸住在森林里。",category:"Plays"},
  {word:"way",phonetic:"/weɪ/",meaning:"方法",example:"No way!",exampleCn:"不可能！",category:"Plays"},
  {word:"no way",phonetic:"/noʊ weɪ/",meaning:"不可能；不行",example:"No way!",exampleCn:"不可能！",category:"Plays"},
  {word:"afraid",phonetic:"/əˈfreɪd/",meaning:"害怕的，恐惧的",example:"I'm afraid.",exampleCn:"我害怕。",category:"Plays"},
  {word:"walk",phonetic:"/wɔːk/",meaning:"走，行走",example:"Let's walk.",exampleCn:"我们走吧。",category:"Plays"},
  {word:"through",phonetic:"/θruː/",meaning:"穿过，通过",example:"Walk through the forest.",exampleCn:"穿过森林。",category:"Plays"},
  {word:"away",phonetic:"/əˈweɪ/",meaning:"离开",example:"Go away!",exampleCn:"走开！",category:"Plays"},
  {word:"whisper",phonetic:"/ˈwɪspər/",meaning:"悄声说；低语",example:"She whispers to me.",exampleCn:"她悄悄对我说。",category:"Plays"},
  {word:"village",phonetic:"/ˈvɪlɪdʒ/",meaning:"乡村，村庄",example:"I live in a village.",exampleCn:"我住在一个村庄。",category:"Plays"},
  {word:"villager",phonetic:"/ˈvɪlɪdʒər/",meaning:"村民",example:"The villager is kind.",exampleCn:"村民很善良。",category:"Plays"},
  {word:"well",phonetic:"/wel/",meaning:"井",example:"There is a well.",exampleCn:"有一口井。",category:"Plays"},
  {word:"pot",phonetic:"/pɒt/",meaning:"锅",example:"A big pot.",exampleCn:"一口大锅。",category:"Plays"},
  {word:"fire",phonetic:"/ˈfaɪər/",meaning:"火；炉火，灶火",example:"Make a fire.",exampleCn:"生火。",category:"Plays"},
  {word:"those",phonetic:"/ðoʊz/",meaning:"那些（that的复数形式）",example:"Those are my books.",exampleCn:"那些是我的书。",category:"Plays"},
  {word:"potato",phonetic:"/pəˈteɪtoʊ/",meaning:"马铃薯，土豆",example:"I like potatoes.",exampleCn:"我喜欢土豆。",category:"Plays"},
  {word:"taste",phonetic:"/teɪst/",meaning:"尝，品尝",example:"Taste this soup.",exampleCn:"尝尝这个汤。",category:"Plays"},
  {word:"bring",phonetic:"/brɪŋ/",meaning:"带来；拿来",example:"Bring me some water.",exampleCn:"给我带些水来。",category:"Plays"},
  {word:"late",phonetic:"/leɪt/",meaning:"晚的，迟的；迟到的",example:"I'm late.",exampleCn:"我迟到了。",category:"Plays"},
  {word:"tomorrow",phonetic:"/təˈmɒroʊ/",meaning:"明天",example:"See you tomorrow.",exampleCn:"明天见。",category:"Plays"},
  {word:"problem",phonetic:"/ˈprɒbləm/",meaning:"问题，难题；困难",example:"No problem.",exampleCn:"没问题。",category:"Plays"},
  {word:"no problem",phonetic:"/noʊ ˈprɒbləm/",meaning:"没问题",example:"No problem!",exampleCn:"没问题！",category:"Plays"},
  {word:"yet",phonetic:"/jet/",meaning:"尚，还，仍",example:"Not yet.",exampleCn:"还没有。",category:"Plays"},
  {word:"already",phonetic:"/ɔːlˈredi/",meaning:"已经",example:"I'm already here.",exampleCn:"我已经在这了。",category:"Plays"},
  {word:"later",phonetic:"/ˈleɪtər/",meaning:"后来，随后，之后",example:"See you later.",exampleCn:"回头见。",category:"Plays"},
  {word:"without",phonetic:"/wɪˈðaʊt/",meaning:"无，没有",example:"Without water.",exampleCn:"没有水。",category:"Plays"},
  {word:"could",phonetic:"/kʊd/",meaning:"能，会，可以（can的过去式）",example:"Could you help me?",exampleCn:"你能帮我吗？",category:"Plays"},
  {word:"sir",phonetic:"/sɜːr/",meaning:"先生",example:"Yes, sir.",exampleCn:"是的，先生。",category:"Plays"},
  {word:"rude",phonetic:"/ruːd/",meaning:"粗鲁的，无礼的",example:"Don't be rude.",exampleCn:"别无礼。",category:"Plays"},
  {word:"bad",phonetic:"/bæd/",meaning:"不好的，糟糕的，坏的",example:"That's bad.",exampleCn:"那太糟糕了。",category:"Plays"},
  {word:"in front of",phonetic:"/ɪn frʌnt əv/",meaning:"在某人/某物的前面",example:"Stand in front of me.",exampleCn:"站在我前面。",category:"Plays"}
];
