// 四年级上册（外研版2024）单词表
const BOOK_TITLE = "📚 四年级上册（外研版）";
const STORAGE_KEY = "vocabApp_grade4a";
const BOOK_WORDS = [
  // Unit 1
  {word:"sport",phonetic:"/spɔːrt/",meaning:"运动",example:"I like sport.",exampleCn:"我喜欢运动。",category:"Unit 1"},
  {word:"jump",phonetic:"/dʒʌmp/",meaning:"跳",example:"I can jump high.",exampleCn:"我能跳得高。",category:"Unit 1"},
  {word:"high",phonetic:"/haɪ/",meaning:"高高地",example:"Jump high!",exampleCn:"跳高！",category:"Unit 1"},
  {word:"far",phonetic:"/fɑːr/",meaning:"远",example:"I can jump far.",exampleCn:"我能跳得远。",category:"Unit 1"},
  {word:"ping-pong",phonetic:"/ˈpɪŋpɒŋ/",meaning:"乒乓球运动",example:"I like ping-pong.",exampleCn:"我喜欢乒乓球。",category:"Unit 1"},
  {word:"volleyball",phonetic:"/ˈvɒlibɔːl/",meaning:"排球（运动）",example:"I play volleyball.",exampleCn:"我打排球。",category:"Unit 1"},
  {word:"first",phonetic:"/fɜːrst/",meaning:"最初",example:"At first, it was hard.",exampleCn:"起初，这很难。",category:"Unit 1"},
  {word:"at first",phonetic:"/æt fɜːrst/",meaning:"起初",example:"At first I didn't like it.",exampleCn:"起初我不喜欢。",category:"Unit 1"},
  {word:"hope",phonetic:"/hoʊp/",meaning:"希望",example:"I hope so.",exampleCn:"我希望如此。",category:"Unit 1"},
  {word:"lose",phonetic:"/luːz/",meaning:"失去",example:"Don't lose hope.",exampleCn:"不要失去希望。",category:"Unit 1"},
  {word:"because",phonetic:"/bɪˈkɒz/",meaning:"因为",example:"I like it because it's fun.",exampleCn:"我喜欢它因为它有趣。",category:"Unit 1"},
  {word:"because of sb/sth",phonetic:"/bɪˈkɒz əv/",meaning:"因为某人/某事物",example:"Because of the rain, we stayed home.",exampleCn:"因为下雨，我们待在家里。",category:"Unit 1"},
  {word:"cancer",phonetic:"/ˈkænsər/",meaning:"癌（症）",example:"He had cancer.",exampleCn:"他得了癌症。",category:"Unit 1"},
  {word:"across",phonetic:"/əˈkrɒs/",meaning:"横跨",example:"He ran across the country.",exampleCn:"他跑遍了全国。",category:"Unit 1"},
  {word:"money",phonetic:"/ˈmʌni/",meaning:"钱",example:"He raised money.",exampleCn:"他筹集了钱。",category:"Unit 1"},
  {word:"hard",phonetic:"/hɑːrd/",meaning:"困难的",example:"It's hard.",exampleCn:"这很难。",category:"Unit 1"},
  {word:"kind",phonetic:"/kaɪnd/",meaning:"友善的",example:"She is kind.",exampleCn:"她很友善。",category:"Unit 1"},
  {word:"keep",phonetic:"/kiːp/",meaning:"持续",example:"Keep trying.",exampleCn:"继续努力。",category:"Unit 1"},
  {word:"month",phonetic:"/mʌnθ/",meaning:"一个月",example:"One month later.",exampleCn:"一个月后。",category:"Unit 1"},
  {word:"ill",phonetic:"/ɪl/",meaning:"生病的",example:"He is ill.",exampleCn:"他生病了。",category:"Unit 1"},
  {word:"year",phonetic:"/jɪər/",meaning:"年；年度",example:"Every year.",exampleCn:"每年。",category:"Unit 1"},
  {word:"remember",phonetic:"/rɪˈmembər/",meaning:"纪念；记住",example:"Remember him.",exampleCn:"记住他。",category:"Unit 1"},
  {word:"fail",phonetic:"/feɪl/",meaning:"失败",example:"Don't be afraid to fail.",exampleCn:"不要害怕失败。",category:"Unit 1"},
  {word:"give",phonetic:"/ɡɪv/",meaning:"给予",example:"Give me the ball.",exampleCn:"把球给我。",category:"Unit 1"},
  {word:"give up",phonetic:"/ɡɪv ʌp/",meaning:"放弃某事",example:"Never give up.",exampleCn:"永不放弃。",category:"Unit 1"},
  {word:"never",phonetic:"/ˈnevər/",meaning:"决不，永不",example:"Never give up.",exampleCn:"永不放弃。",category:"Unit 1"},
  {word:"try",phonetic:"/traɪ/",meaning:"努力；尝试",example:"Try again.",exampleCn:"再试一次。",category:"Unit 1"},
  {word:"player",phonetic:"/ˈpleɪər/",meaning:"运动员，选手",example:"He is a good player.",exampleCn:"他是一个好选手。",category:"Unit 1"},
  {word:"ability",phonetic:"/əˈbɪləti/",meaning:"能力",example:"He has great ability.",exampleCn:"他能力很强。",category:"Unit 1"},

  // Unit 2
  {word:"phew",phonetic:"/fjuː/",meaning:"啊，哟，唉",example:"Phew! I'm tired.",exampleCn:"唉！我累了。",category:"Unit 2"},
  {word:"wash",phonetic:"/wɒʃ/",meaning:"洗",example:"Wash the dishes.",exampleCn:"洗碗。",category:"Unit 2"},
  {word:"dish",phonetic:"/dɪʃ/",meaning:"盘子，碟子",example:"Put the dish on the table.",exampleCn:"把盘子放在桌上。",category:"Unit 2"},
  {word:"feed",phonetic:"/fiːd/",meaning:"喂养，给……食物",example:"Feed the dog.",exampleCn:"喂狗。",category:"Unit 2"},
  {word:"sweep",phonetic:"/swiːp/",meaning:"扫，打扫",example:"Sweep the floor.",exampleCn:"扫地。",category:"Unit 2"},
  {word:"floor",phonetic:"/flɔːr/",meaning:"地板，地面",example:"Clean the floor.",exampleCn:"擦地板。",category:"Unit 2"},
  {word:"rubbish",phonetic:"/ˈrʌbɪʃ/",meaning:"垃圾",example:"Take out the rubbish.",exampleCn:"倒垃圾。",category:"Unit 2"},
  {word:"chore",phonetic:"/tʃɔːr/",meaning:"家庭杂务",example:"I do chores at home.",exampleCn:"我在家做家务。",category:"Unit 2"},
  {word:"to-do list",phonetic:"/tuː duː lɪst/",meaning:"待办清单",example:"Make a to-do list.",exampleCn:"列一个待办清单。",category:"Unit 2"},
  {word:"may",phonetic:"/meɪ/",meaning:"可以（表示允许某人做某事）",example:"May I help you?",exampleCn:"我可以帮你吗？",category:"Unit 2"},
  {word:"outside",phonetic:"/ˌaʊtˈsaɪd/",meaning:"在室外",example:"Let's go outside.",exampleCn:"我们去外面吧。",category:"Unit 2"},
  {word:"tidy",phonetic:"/ˈtaɪdi/",meaning:"整理，收拾",example:"Tidy your room.",exampleCn:"整理你的房间。",category:"Unit 2"},
  {word:"easy",phonetic:"/ˈiːzi/",meaning:"容易的",example:"It's easy.",exampleCn:"这很容易。",category:"Unit 2"},
  {word:"clean",phonetic:"/kliːn/",meaning:"清洁的，干净的",example:"Keep it clean.",exampleCn:"保持干净。",category:"Unit 2"},
  {word:"woof",phonetic:"/wʊf/",meaning:"汪汪（形容狗叫声）",example:"Woof! Woof!",exampleCn:"汪汪！",category:"Unit 2"},
  {word:"job",phonetic:"/dʒɒb/",meaning:"任务，事情",example:"Good job!",exampleCn:"干得好！",category:"Unit 2"},
  {word:"good job",phonetic:"/ɡʊd dʒɒb/",meaning:"干得好，真不错",example:"Good job!",exampleCn:"干得好！",category:"Unit 2"},
  {word:"dirty",phonetic:"/ˈdɜːrti/",meaning:"脏的",example:"The floor is dirty.",exampleCn:"地板很脏。",category:"Unit 2"},
  {word:"desk",phonetic:"/desk/",meaning:"书桌，写字台",example:"Clean the desk.",exampleCn:"擦桌子。",category:"Unit 2"},
  {word:"wall",phonetic:"/wɔːl/",meaning:"墙",example:"Don't draw on the wall.",exampleCn:"别在墙上画。",category:"Unit 2"},
  {word:"again",phonetic:"/əˈɡen/",meaning:"再一次",example:"Try again.",exampleCn:"再试一次。",category:"Unit 2"},
  {word:"also",phonetic:"/ˈɔːlsoʊ/",meaning:"除此之外，还",example:"I also like it.",exampleCn:"我也喜欢。",category:"Unit 2"},
  {word:"problem",phonetic:"/ˈprɒbləm/",meaning:"问题",example:"No problem.",exampleCn:"没问题。",category:"Unit 2"},
  {word:"finish",phonetic:"/ˈfɪnɪʃ/",meaning:"完成，做完",example:"Finish your homework.",exampleCn:"完成你的作业。",category:"Unit 2"},
  {word:"sunshine",phonetic:"/ˈsʌnʃaɪn/",meaning:"阳光；幸福",example:"You are my sunshine.",exampleCn:"你是我的阳光。",category:"Unit 2"},
  {word:"sometimes",phonetic:"/ˈsʌmtaɪmz/",meaning:"有时",example:"Sometimes I help mum.",exampleCn:"有时我帮妈妈。",category:"Unit 2"},
  {word:"feel",phonetic:"/fiːl/",meaning:"感受到，觉得",example:"I feel happy.",exampleCn:"我感到开心。",category:"Unit 2"},
  {word:"tired",phonetic:"/ˈtaɪərd/",meaning:"困倦的；疲惫的，累的",example:"I'm tired.",exampleCn:"我累了。",category:"Unit 2"},
  {word:"helpful",phonetic:"/ˈhelpfl/",meaning:"有用的，有帮助的",example:"You are helpful.",exampleCn:"你很有帮助。",category:"Unit 2"},
  {word:"warm",phonetic:"/wɔːrm/",meaning:"（使）变暖和；温暖的",example:"It's warm today.",exampleCn:"今天很暖和。",category:"Unit 2"},
  {word:"warm up",phonetic:"/wɔːrm ʌp/",meaning:"（使）变暖",example:"Warm up the soup.",exampleCn:"把汤热一下。",category:"Unit 2"},
  {word:"water",phonetic:"/ˈwɔːtər/",meaning:"给……浇水",example:"Water the flowers.",exampleCn:"给花浇水。",category:"Unit 2"},
  {word:"yard",phonetic:"/jɑːrd/",meaning:"庭院",example:"Play in the yard.",exampleCn:"在院子里玩。",category:"Unit 2"},
  {word:"helper",phonetic:"/ˈhelpər/",meaning:"帮手；助手",example:"You are a good helper.",exampleCn:"你是个好帮手。",category:"Unit 2"},
  {word:"pick",phonetic:"/pɪk/",meaning:"采，摘",example:"Pick the flowers.",exampleCn:"摘花。",category:"Unit 2"},
  {word:"pig",phonetic:"/pɪɡ/",meaning:"猪",example:"Feed the pig.",exampleCn:"喂猪。",category:"Unit 2"},
  {word:"cow",phonetic:"/kaʊ/",meaning:"母牛；奶牛",example:"Feed the cow.",exampleCn:"喂牛。",category:"Unit 2"},
  {word:"collect",phonetic:"/kəˈlekt/",meaning:"收集，采集",example:"Collect the eggs.",exampleCn:"收鸡蛋。",category:"Unit 2"},
  {word:"cut",phonetic:"/kʌt/",meaning:"修剪",example:"Cut the grass.",exampleCn:"修剪草坪。",category:"Unit 2"},
  {word:"grass",phonetic:"/ɡrɑːs/",meaning:"草，青草",example:"Cut the grass.",exampleCn:"修剪草坪。",category:"Unit 2"},

  // Unit 3
  {word:"weather",phonetic:"/ˈweðər/",meaning:"天气",example:"What's the weather like?",exampleCn:"天气怎么样？",category:"Unit 3"},
  {word:"sunny",phonetic:"/ˈsʌni/",meaning:"阳光充足的",example:"It's sunny today.",exampleCn:"今天阳光充足。",category:"Unit 3"},
  {word:"cloud",phonetic:"/klaʊd/",meaning:"云",example:"Look at the clouds.",exampleCn:"看那些云。",category:"Unit 3"},
  {word:"by",phonetic:"/baɪ/",meaning:"经过",example:"A cloud goes by.",exampleCn:"一朵云飘过。",category:"Unit 3"},
  {word:"cloudy",phonetic:"/ˈklaʊdi/",meaning:"多云的，阴天的",example:"It's cloudy today.",exampleCn:"今天多云。",category:"Unit 3"},
  {word:"wind",phonetic:"/wɪnd/",meaning:"风",example:"The wind is strong.",exampleCn:"风很大。",category:"Unit 3"},
  {word:"blow",phonetic:"/bloʊ/",meaning:"吹，刮",example:"The wind blows.",exampleCn:"风在吹。",category:"Unit 3"},
  {word:"windy",phonetic:"/ˈwɪndi/",meaning:"风大的；多风的",example:"It's windy today.",exampleCn:"今天风很大。",category:"Unit 3"},
  {word:"rain",phonetic:"/reɪn/",meaning:"雨",example:"It's going to rain.",exampleCn:"要下雨了。",category:"Unit 3"},
  {word:"rainy",phonetic:"/ˈreɪni/",meaning:"多雨的",example:"It's a rainy day.",exampleCn:"这是一个雨天。",category:"Unit 3"},
  {word:"snow",phonetic:"/snoʊ/",meaning:"雪",example:"It's going to snow.",exampleCn:"要下雪了。",category:"Unit 3"},
  {word:"any",phonetic:"/ˈeni/",meaning:"任何一个",example:"Is there any rain?",exampleCn:"有雨吗？",category:"Unit 3"},
  {word:"cold",phonetic:"/koʊld/",meaning:"冷的，寒冷的",example:"It's cold today.",exampleCn:"今天很冷。",category:"Unit 3"},
  {word:"or",phonetic:"/ɔːr/",meaning:"或者",example:"Sunny or cloudy?",exampleCn:"晴天还是阴天？",category:"Unit 3"},
  {word:"enjoy",phonetic:"/ɪnˈdʒɔɪ/",meaning:"享受……的乐趣",example:"Enjoy the sunshine.",exampleCn:"享受阳光。",category:"Unit 3"},
  {word:"diary",phonetic:"/ˈdaɪəri/",meaning:"日记",example:"Write a diary.",exampleCn:"写日记。",category:"Unit 3"},
  {word:"special",phonetic:"/ˈspeʃl/",meaning:"特殊的，特别的",example:"It's a special day.",exampleCn:"这是特别的一天。",category:"Unit 3"},
  {word:"teacher",phonetic:"/ˈtiːtʃər/",meaning:"老师",example:"She is my teacher.",exampleCn:"她是我的老师。",category:"Unit 3"},
  {word:"taste",phonetic:"/teɪst/",meaning:"有……的味道",example:"Taste this cake.",exampleCn:"尝尝这个蛋糕。",category:"Unit 3"},
  {word:"ice cream",phonetic:"/aɪs kriːm/",meaning:"冰激凌，雪糕",example:"I like ice cream.",exampleCn:"我喜欢冰激凌。",category:"Unit 3"},
  {word:"real",phonetic:"/riːl/",meaning:"真的，真正的",example:"Is it real?",exampleCn:"这是真的吗？",category:"Unit 3"},
  {word:"later",phonetic:"/ˈleɪtər/",meaning:"之后",example:"See you later.",exampleCn:"回头见。",category:"Unit 3"},
  {word:"surprise",phonetic:"/sərˈpraɪz/",meaning:"意想不到的事",example:"What a surprise!",exampleCn:"真是意想不到！",category:"Unit 3"},
  {word:"coat",phonetic:"/koʊt/",meaning:"外套",example:"Put on your coat.",exampleCn:"穿上你的外套。",category:"Unit 3"},
  {word:"turn",phonetic:"/tɜːrn/",meaning:"转身，转动",example:"Turn around.",exampleCn:"转过身。",category:"Unit 3"},
  {word:"turn on",phonetic:"/tɜːrn ɒn/",meaning:"打开",example:"Turn on the TV.",exampleCn:"打开电视。",category:"Unit 3"},
  {word:"TV",phonetic:"/tiːˈviː/",meaning:"电视",example:"Watch TV.",exampleCn:"看电视。",category:"Unit 3"},
  {word:"report",phonetic:"/rɪˈpɔːrt/",meaning:"报道",example:"A weather report.",exampleCn:"天气预报。",category:"Unit 3"},

  // Unit 4
  {word:"season",phonetic:"/ˈsiːzn/",meaning:"季节",example:"What's your favourite season?",exampleCn:"你最喜欢的季节是什么？",category:"Unit 4"},
  {word:"spring",phonetic:"/sprɪŋ/",meaning:"春天，春季",example:"I like spring.",exampleCn:"我喜欢春天。",category:"Unit 4"},
  {word:"summer",phonetic:"/ˈsʌmər/",meaning:"夏天，夏季",example:"Summer is hot.",exampleCn:"夏天很热。",category:"Unit 4"},
  {word:"autumn",phonetic:"/ˈɔːtəm/",meaning:"秋天，秋季",example:"Autumn is cool.",exampleCn:"秋天很凉爽。",category:"Unit 4"},
  {word:"winter",phonetic:"/ˈwɪntər/",meaning:"冬天，冬季",example:"Winter is cold.",exampleCn:"冬天很冷。",category:"Unit 4"},
  {word:"favourite",phonetic:"/ˈfeɪvərɪt/",meaning:"最喜欢的",example:"What's your favourite season?",exampleCn:"你最喜欢的季节是什么？",category:"Unit 4"},
  {word:"birthday",phonetic:"/ˈbɜːrθdeɪ/",meaning:"生日",example:"Happy birthday!",exampleCn:"生日快乐！",category:"Unit 4"},
  {word:"fly",phonetic:"/flaɪ/",meaning:"放飞",example:"Fly a kite.",exampleCn:"放风筝。",category:"Unit 4"},
  {word:"fly kites",phonetic:"/flaɪ kaɪts/",meaning:"放风筝",example:"We fly kites in spring.",exampleCn:"我们春天放风筝。",category:"Unit 4"},
  {word:"snowstorm",phonetic:"/ˈsnoʊstɔːrm/",meaning:"雪暴，暴风雪",example:"There is a snowstorm.",exampleCn:"有暴风雪。",category:"Unit 4"},
  {word:"beach",phonetic:"/biːtʃ/",meaning:"海滩",example:"Let's go to the beach.",exampleCn:"我们去海滩吧。",category:"Unit 4"},
  {word:"sea",phonetic:"/siː/",meaning:"海，海洋",example:"I like the sea.",exampleCn:"我喜欢大海。",category:"Unit 4"},
  {word:"equator",phonetic:"/ɪˈkweɪtər/",meaning:"赤道",example:"It's hot near the equator.",exampleCn:"赤道附近很热。",category:"Unit 4"},
  {word:"round",phonetic:"/raʊnd/",meaning:"到处",example:"Look round.",exampleCn:"到处看看。",category:"Unit 4"},
  {word:"quite",phonetic:"/kwaɪt/",meaning:"非常，十分",example:"It's quite cold.",exampleCn:"非常冷。",category:"Unit 4"},
  {word:"join",phonetic:"/dʒɔɪn/",meaning:"参与，加入",example:"Join us!",exampleCn:"加入我们！",category:"Unit 4"},

  // Unit 5
  {word:"bus",phonetic:"/bʌs/",meaning:"公交车，公共汽车",example:"Take the bus.",exampleCn:"坐公交车。",category:"Unit 5"},
  {word:"car",phonetic:"/kɑːr/",meaning:"汽车",example:"Go by car.",exampleCn:"坐汽车去。",category:"Unit 5"},
  {word:"train",phonetic:"/treɪn/",meaning:"火车，列车",example:"Take the train.",exampleCn:"坐火车。",category:"Unit 5"},
  {word:"city",phonetic:"/ˈsɪti/",meaning:"城市",example:"I live in a big city.",exampleCn:"我住在一个大城市。",category:"Unit 5"},
  {word:"town",phonetic:"/taʊn/",meaning:"镇，城镇",example:"It's a small town.",exampleCn:"这是一个小镇。",category:"Unit 5"},
  {word:"plane",phonetic:"/pleɪn/",meaning:"飞机",example:"Go by plane.",exampleCn:"坐飞机去。",category:"Unit 5"},
  {word:"sky",phonetic:"/skaɪ/",meaning:"天，天空",example:"The sky is blue.",exampleCn:"天空是蓝色的。",category:"Unit 5"},
  {word:"ship",phonetic:"/ʃɪp/",meaning:"大船",example:"Go by ship.",exampleCn:"坐船去。",category:"Unit 5"},
  {word:"place",phonetic:"/pleɪs/",meaning:"地方，地点",example:"This is a nice place.",exampleCn:"这是一个好地方。",category:"Unit 5"},
  {word:"near",phonetic:"/nɪr/",meaning:"（距离）近的",example:"It's near my home.",exampleCn:"它离我家很近。",category:"Unit 5"},
  {word:"travel",phonetic:"/ˈtrævl/",meaning:"旅行",example:"I like to travel.",exampleCn:"我喜欢旅行。",category:"Unit 5"},
  {word:"way",phonetic:"/weɪ/",meaning:"方式，方法",example:"What's the best way?",exampleCn:"最好的方式是什么？",category:"Unit 5"},
  {word:"picnic",phonetic:"/ˈpɪknɪk/",meaning:"野餐",example:"Let's have a picnic.",exampleCn:"我们去野餐吧。",category:"Unit 5"},
  {word:"minute",phonetic:"/ˈmɪnɪt/",meaning:"分钟",example:"Wait a minute.",exampleCn:"等一分钟。",category:"Unit 5"},
  {word:"wear",phonetic:"/weər/",meaning:"穿",example:"Wear your coat.",exampleCn:"穿上你的外套。",category:"Unit 5"},
  {word:"live",phonetic:"/lɪv/",meaning:"住，居住",example:"I live in Beijing.",exampleCn:"我住在北京。",category:"Unit 5"},
  {word:"away",phonetic:"/əˈweɪ/",meaning:"离开，相距",example:"It's far away.",exampleCn:"它很远。",category:"Unit 5"},
  {word:"truck",phonetic:"/trʌk/",meaning:"货车，卡车",example:"A big truck.",exampleCn:"一辆大卡车。",category:"Unit 5"},
  {word:"bamboo",phonetic:"/bæmˈbuː/",meaning:"竹，竹子",example:"Pandas eat bamboo.",exampleCn:"熊猫吃竹子。",category:"Unit 5"},
  {word:"airport",phonetic:"/ˈeərpɔːrt/",meaning:"机场",example:"Go to the airport.",exampleCn:"去机场。",category:"Unit 5"},
  {word:"bike",phonetic:"/baɪk/",meaning:"自行车",example:"Ride a bike.",exampleCn:"骑自行车。",category:"Unit 5"},
  {word:"ring",phonetic:"/rɪŋ/",meaning:"（钟、铃）鸣响",example:"The bell rings.",exampleCn:"铃响了。",category:"Unit 5"},
  {word:"beep",phonetic:"/biːp/",meaning:"（使）（汽车喇叭）鸣响",example:"Beep beep!",exampleCn:"嘟嘟！",category:"Unit 5"},
  {word:"subway",phonetic:"/ˈsʌbweɪ/",meaning:"地铁",example:"Take the subway.",exampleCn:"坐地铁。",category:"Unit 5"},
  {word:"whoosh",phonetic:"/wʊʃ/",meaning:"（呼呼地）飞快移动",example:"Whoosh! The train goes fast.",exampleCn:"呼！火车飞快地开过。",category:"Unit 5"},
  {word:"tram",phonetic:"/træm/",meaning:"有轨电车",example:"Take the tram.",exampleCn:"坐有轨电车。",category:"Unit 5"},
  {word:"chug",phonetic:"/tʃʌɡ/",meaning:"（汽车、火车等）突突地缓慢前进",example:"The train chugs along.",exampleCn:"火车突突地前进。",category:"Unit 5"},

  // Unit 6
  {word:"wheel",phonetic:"/wiːl/",meaning:"车轮",example:"The wheel turns.",exampleCn:"车轮转动。",category:"Unit 6"},
  {word:"left",phonetic:"/left/",meaning:"向左，朝左",example:"Turn left.",exampleCn:"向左转。",category:"Unit 6"},
  {word:"straight",phonetic:"/streɪt/",meaning:"笔直地",example:"Go straight.",exampleCn:"直走。",category:"Unit 6"},
  {word:"library",phonetic:"/ˈlaɪbrəri/",meaning:"图书室；图书馆",example:"Go to the library.",exampleCn:"去图书馆。",category:"Unit 6"},
  {word:"centre",phonetic:"/ˈsentər/",meaning:"中心",example:"The city centre.",exampleCn:"市中心。",category:"Unit 6"},
  {word:"cinema",phonetic:"/ˈsɪnəmə/",meaning:"电影院",example:"Let's go to the cinema.",exampleCn:"我们去电影院吧。",category:"Unit 6"},
  {word:"hospital",phonetic:"/ˈhɒspɪtl/",meaning:"医院",example:"Go to the hospital.",exampleCn:"去医院。",category:"Unit 6"},
  {word:"supermarket",phonetic:"/ˈsuːpərmɑːrkɪt/",meaning:"超市",example:"Go to the supermarket.",exampleCn:"去超市。",category:"Unit 6"},
  {word:"museum",phonetic:"/mjuˈziːəm/",meaning:"博物馆，博物院",example:"Visit the museum.",exampleCn:"参观博物馆。",category:"Unit 6"},
  {word:"tomorrow",phonetic:"/təˈmɒroʊ/",meaning:"明天",example:"See you tomorrow.",exampleCn:"明天见。",category:"Unit 6"},
  {word:"woman",phonetic:"/ˈwʊmən/",meaning:"女性，女人",example:"The woman is kind.",exampleCn:"这位女士很友善。",category:"Unit 6"},
  {word:"excuse",phonetic:"/ɪkˈskjuːz/",meaning:"原谅",example:"Excuse me.",exampleCn:"劳驾。",category:"Unit 6"},
  {word:"excuse me",phonetic:"/ɪkˈskjuːz miː/",meaning:"劳驾",example:"Excuse me, where is the library?",exampleCn:"劳驾，图书馆在哪里？",category:"Unit 6"},
  {word:"wish",phonetic:"/wɪʃ/",meaning:"希望，愿望",example:"I wish you well.",exampleCn:"我祝你好。",category:"Unit 6"},
  {word:"true",phonetic:"/truː/",meaning:"真的，真实的",example:"Is it true?",exampleCn:"这是真的吗？",category:"Unit 6"},
  {word:"step",phonetic:"/step/",meaning:"步",example:"Take one step.",exampleCn:"走一步。",category:"Unit 6"},
  {word:"own",phonetic:"/oʊn/",meaning:"自己的",example:"My own room.",exampleCn:"我自己的房间。",category:"Unit 6"},
  {word:"cross",phonetic:"/krɒs/",meaning:"横穿",example:"Cross the road.",exampleCn:"过马路。",category:"Unit 6"},
  {word:"careful",phonetic:"/ˈkeərfl/",meaning:"谨慎的",example:"Be careful!",exampleCn:"小心！",category:"Unit 6"},
  {word:"be careful",phonetic:"/biː ˈkeərfl/",meaning:"当心，小心",example:"Be careful crossing the road.",exampleCn:"过马路要小心。",category:"Unit 6"},
  {word:"underground",phonetic:"/ˌʌndərˈɡraʊnd/",meaning:"在地（面）下",example:"The underground train.",exampleCn:"地铁。",category:"Unit 6"},

  // Plays 课本剧词汇
  {word:"proud",phonetic:"/praʊd/",meaning:"自豪的，得意的",example:"I'm proud of you.",exampleCn:"我为你骄傲。",category:"Plays"},
  {word:"take off",phonetic:"/teɪk ɒf/",meaning:"脱下，脱掉（衣物）",example:"Take off your coat.",exampleCn:"脱掉你的外套。",category:"Plays"},
  {word:"of course",phonetic:"/əv kɔːrs/",meaning:"当然",example:"Of course!",exampleCn:"当然！",category:"Plays"},
  {word:"go ahead",phonetic:"/ɡoʊ əˈhed/",meaning:"请吧",example:"Go ahead.",exampleCn:"请吧。",category:"Plays"},
  {word:"shine",phonetic:"/ʃaɪn/",meaning:"发光，发亮",example:"The sun shines.",exampleCn:"太阳发光。",category:"Plays"},
  {word:"yay",phonetic:"/jeɪ/",meaning:"耶",example:"Yay! We won!",exampleCn:"耶！我们赢了！",category:"Plays"},
  {word:"skiing",phonetic:"/ˈskiːɪŋ/",meaning:"滑雪运动",example:"I like skiing.",exampleCn:"我喜欢滑雪。",category:"Plays"},
  {word:"inside",phonetic:"/ɪnˈsaɪd/",meaning:"在内部",example:"Come inside.",exampleCn:"进来。",category:"Plays"},
  {word:"cry",phonetic:"/kraɪ/",meaning:"哭，哭泣",example:"Don't cry.",exampleCn:"别哭。",category:"Plays"},
  {word:"I'm fine.",phonetic:"/aɪm faɪn/",meaning:"我很好。",example:"I'm fine, thank you.",exampleCn:"我很好，谢谢。",category:"Plays"},
  {word:"restaurant",phonetic:"/ˈrestərɒnt/",meaning:"饭店，餐馆",example:"Let's go to the restaurant.",exampleCn:"我们去餐馆吧。",category:"Plays"},
  {word:"duck",phonetic:"/dʌk/",meaning:"鸭",example:"Look at the duck.",exampleCn:"看那只鸭子。",category:"Plays"},
  {word:"river",phonetic:"/ˈrɪvər/",meaning:"江，河",example:"The river is long.",exampleCn:"这条河很长。",category:"Plays"},
  {word:"at last",phonetic:"/æt lɑːst/",meaning:"终于",example:"At last, we're here!",exampleCn:"终于，我们到了！",category:"Plays"}
];
